default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  min_messages: WARNING
  username: postgres
  host: <%= ENV['DOCKERRAILS_DB_1_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['DOCKERRAILS_DB_1_PORT_5432_TCP_PORT'] %>

development:
  <<: *default
  database: docker_rails_development

test:
  <<: *default
  database: docker_rails_test

production:
  <<: *default
  database: docker_rails_production
  username: docker_rails
  password: <%= ENV['DOCKER_RAILS_DATABASE_PASSWORD'] %>
