# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 844475a501db176d03fe5a35a81a908df2a8f4142a0d9b49926c203b076d3271db15451cd1926e8a3be49a9deadd4e1500a434d730cf8a7565645c8947c33559

test:
  secret_key_base: 5fc03ddbba31ffa90f206da14bbc821cdc7776dd7ffcb5c3397403e3e480846c4a8d72fe105632ade3de2e619ba641c5b01ef3484fd3e861c4303e32245e40c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
